server:
  port: 8020

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user
          predicates:
          - Path= /api/users
          - Method= GET
          uri: lb://ms-user


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka





